namespace: myapp
output:
  file_path: Fluid-Attacks-Results.csv
  format: CSV
working_dir: .
file_size_limit: false
sast:
  include:
    - .
sca:
  include:
    - .
apk:
  include:
    - .
debug: true
